---
# handlers file for ansible-applyupdates


- name: Restart server
  command: shutdown -r now "Reboot triggered by Ansible"
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for server to restart
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port: "{{ ansible_ssh_port }}"
    delay: 1
    timeout: 300
  sudo: false